
language: node_js
node_js:
  - '4.4'

before_script:
  - export DISPLAY=:99.0
  - export COVERALLS_SERVICE_NAME=travis-ci
  - sh -e /etc/init.d/xvfb start
  - npm start > /dev/null &
  - npm run update-webdriver
  # - npm run install-bower-dependencies
  # - npm run install-selenium-dependencies
  - sleep 1 # give server time to start

script:
  - node_modules/.bin/karma start test/karma.conf.js --no-auto-watch --single-run --reporters=dots --browsers=Firefox
  - node_modules/.bin/protractor test/protractor.conf.js --browser=firefox

after_script:
  - cat coverage/*/lcov.info | ./node_modules/coveralls/bin/coveralls.js
